name: debuild process
on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-24.04
    #runs-on: [self-hosted, reactive, amd64, large-tiobe, noble]
    
    steps:
    - name: Build configuration
      run: |  
          sudo apt-get update -y || true
          #Debuild and coverage dependecies
          sudo apt install -y devscripts build-essential debhelper checkinstall gcovr
          #Package build dependencies
          sudo apt install -y dh-sequence-gnome libadwaita-1-dev libgtk-4-dev libxkbcommon-dev meson
          
    - name: Checkout repository
      uses: actions/checkout@v3
     
    - name: Build package
      run: |
          cd tecla-46.0/
          debuild -us -uc    
